version: "3.3"

services:
  database:
    image: postgres
    restart: on-failure
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_PASSWORD=projeto
      - POSTGRES_USER=projeto
      - POSTGRES_PORT=5432
      - POSTGRES_DB=blog_bd
    ports:
      - 5432:5432
    expose:
      - "5432"