# fly.toml app configuration file generated for blog-platform-2 on 2024-10-20T14:49:44-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'blog-platform-2'
primary_region = 'gru'
console_command = '/code/manage.py shell'

[build]

[deploy]
   release_command = "./pos-release.sh"

[env]
  PORT = '8000'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'

[[statics]]
  guest_path = '/code/static'
  url_prefix = '/static/'
