# Generated by Django 5.1.2 on 2024-10-09 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=2, upload_to='post/'),
            preserve_default=False,
        ),
    ]
